Update to qemu libvirt hook

diff --git a/vfio/libvirt/qemu b/vfio/libvirt/qemu
--- a/vfio/libvirt/qemu
+++ b/vfio/libvirt/qemu
@@ -16,7 +16,7 @@ VM_IP="192.168.122.76"
 
 
 # List of VMS where performance is critical
-VMS_FOR_SHIELDING="win10 win10-nvme win10-kvmfr macos macosHS vfio-q35-win10 win10-nvme-q35-native"
+VMS_FOR_SHIELDING="win10 win10-nvme win10-kvmfr macos macosHS vfio-q35-win10 win10-nvme-q35-native win10-nvme-q35-qemu"
 
 # Ryzen 16 threads
 TOTAL_CORES='0-15'
@@ -76,6 +76,17 @@ start(){
             echo "set mask $GUEST_CORES_MASK to irq $i"
             echo "$GUEST_CORES_MASK" >/proc/irq/$i/smp_affinity
         done
+    fi
+
+    # change qemu to use realtime scheduling
+    QEMU=qemu-system-x86_64
+    if pid=$(pidof $QEMU); then
+        chrt -f -p 1 $pid
+        if [ $? = 0 ]; then
+            echo "$(date) INFO: real-time scheduling SET for $QEMU pid: $pid" >> $LOG
+        else
+            echo "$(date) ERROR: real-time scheduling FAILED for $QEMU pid: $pid" >> $LOG
+        fi
     fi
 }
 
